/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/@/': RouteRecordInfo<'/@/', '/@', Record<never, never>, Record<never, never>>,
    '/@/[profile]': RouteRecordInfo<'/@/[profile]', '/@/:profile', { profile: ParamValue<true> }, { profile: ParamValue<false> }>,
    '/administration/': RouteRecordInfo<'/administration/', '/administration', Record<never, never>, Record<never, never>>,
    '/administration/settings/': RouteRecordInfo<'/administration/settings/', '/administration/settings', Record<never, never>, Record<never, never>>,
    '/administration/settings/privacy-policy': RouteRecordInfo<'/administration/settings/privacy-policy', '/administration/settings/privacy-policy', Record<never, never>, Record<never, never>>,
    '/administration/settings/recovery': RouteRecordInfo<'/administration/settings/recovery', '/administration/settings/recovery', Record<never, never>, Record<never, never>>,
    '/administration/settings/terms-of-service': RouteRecordInfo<'/administration/settings/terms-of-service', '/administration/settings/terms-of-service', Record<never, never>, Record<never, never>>,
    '/administration/tests': RouteRecordInfo<'/administration/tests', '/administration/tests', Record<never, never>, Record<never, never>>,
    '/canvas': RouteRecordInfo<'/canvas', '/canvas', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/code': RouteRecordInfo<'/code', '/code', Record<never, never>, Record<never, never>>,
    '/downloads': RouteRecordInfo<'/downloads', '/downloads', Record<never, never>, Record<never, never>>,
    '/drive': RouteRecordInfo<'/drive', '/drive', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/information': RouteRecordInfo<'/information', '/information', Record<never, never>, Record<never, never>>,
    '/inventory': RouteRecordInfo<'/inventory', '/inventory', Record<never, never>, Record<never, never>>,
    '/lists': RouteRecordInfo<'/lists', '/lists', Record<never, never>, Record<never, never>>,
    '/map': RouteRecordInfo<'/map', '/map', Record<never, never>, Record<never, never>>,
    '/meta-data': RouteRecordInfo<'/meta-data', '/meta-data', Record<never, never>, Record<never, never>>,
    '/my-space/': RouteRecordInfo<'/my-space/', '/my-space', Record<never, never>, Record<never, never>>,
    '/my-space/friends/': RouteRecordInfo<'/my-space/friends/', '/my-space/friends', Record<never, never>, Record<never, never>>,
    '/my-space/friends/[id]': RouteRecordInfo<'/my-space/friends/[id]', '/my-space/friends/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/notifications': RouteRecordInfo<'/notifications', '/notifications', Record<never, never>, Record<never, never>>,
    '/nutrition': RouteRecordInfo<'/nutrition', '/nutrition', Record<never, never>, Record<never, never>>,
    '/others/messanger': RouteRecordInfo<'/others/messanger', '/others/messanger', Record<never, never>, Record<never, never>>,
    '/others/news': RouteRecordInfo<'/others/news', '/others/news', Record<never, never>, Record<never, never>>,
    '/others/nucet': RouteRecordInfo<'/others/nucet', '/others/nucet', Record<never, never>, Record<never, never>>,
    '/others/raport-designer': RouteRecordInfo<'/others/raport-designer', '/others/raport-designer', Record<never, never>, Record<never, never>>,
    '/others/vote-creator': RouteRecordInfo<'/others/vote-creator', '/others/vote-creator', Record<never, never>, Record<never, never>>,
    '/referencer': RouteRecordInfo<'/referencer', '/referencer', Record<never, never>, Record<never, never>>,
    '/reports': RouteRecordInfo<'/reports', '/reports', Record<never, never>, Record<never, never>>,
    '/Servers/': RouteRecordInfo<'/Servers/', '/Servers', Record<never, never>, Record<never, never>>,
    '/Servers/[id]': RouteRecordInfo<'/Servers/[id]', '/Servers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Servers/create-server': RouteRecordInfo<'/Servers/create-server', '/Servers/create-server', Record<never, never>, Record<never, never>>,
    '/streaming': RouteRecordInfo<'/streaming', '/streaming', Record<never, never>, Record<never, never>>,
    '/tasks': RouteRecordInfo<'/tasks', '/tasks', Record<never, never>, Record<never, never>>,
    '/tier-list/': RouteRecordInfo<'/tier-list/', '/tier-list', Record<never, never>, Record<never, never>>,
    '/tier-list/[id]': RouteRecordInfo<'/tier-list/[id]', '/tier-list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/universe/': RouteRecordInfo<'/universe/', '/universe', Record<never, never>, Record<never, never>>,
    '/universe/map/': RouteRecordInfo<'/universe/map/', '/universe/map', Record<never, never>, Record<never, never>>,
    '/universe/wiki/': RouteRecordInfo<'/universe/wiki/', '/universe/wiki', Record<never, never>, Record<never, never>>,
    '/universe/wiki/characters/': RouteRecordInfo<'/universe/wiki/characters/', '/universe/wiki/characters', Record<never, never>, Record<never, never>>,
    '/universe/wiki/regions/': RouteRecordInfo<'/universe/wiki/regions/', '/universe/wiki/regions', Record<never, never>, Record<never, never>>,
  }
}
