/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDriveUploadPostRequestLength
 */
export interface ApiDriveUploadPostRequestLength {
}

/**
 * Check if a given object implements the ApiDriveUploadPostRequestLength interface.
 */
export function instanceOfApiDriveUploadPostRequestLength(value: object): value is ApiDriveUploadPostRequestLength {
    return true;
}

export function ApiDriveUploadPostRequestLengthFromJSON(json: any): ApiDriveUploadPostRequestLength {
    return ApiDriveUploadPostRequestLengthFromJSONTyped(json, false);
}

export function ApiDriveUploadPostRequestLengthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDriveUploadPostRequestLength {
    return json;
}

export function ApiDriveUploadPostRequestLengthToJSON(json: any): ApiDriveUploadPostRequestLength {
    return ApiDriveUploadPostRequestLengthToJSONTyped(json, false);
}

export function ApiDriveUploadPostRequestLengthToJSONTyped(value?: ApiDriveUploadPostRequestLength | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

