/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUsersGetGetPageSizeParameter
 */
export interface ApiUsersGetGetPageSizeParameter {
}

/**
 * Check if a given object implements the ApiUsersGetGetPageSizeParameter interface.
 */
export function instanceOfApiUsersGetGetPageSizeParameter(value: object): value is ApiUsersGetGetPageSizeParameter {
    return true;
}

export function ApiUsersGetGetPageSizeParameterFromJSON(json: any): ApiUsersGetGetPageSizeParameter {
    return ApiUsersGetGetPageSizeParameterFromJSONTyped(json, false);
}

export function ApiUsersGetGetPageSizeParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersGetGetPageSizeParameter {
    return json;
}

export function ApiUsersGetGetPageSizeParameterToJSON(json: any): ApiUsersGetGetPageSizeParameter {
    return ApiUsersGetGetPageSizeParameterToJSONTyped(json, false);
}

export function ApiUsersGetGetPageSizeParameterToJSONTyped(value?: ApiUsersGetGetPageSizeParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

