/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';

/**
 * 
 * @export
 * @interface CommunityModel
 */
export interface CommunityModel {
    /**
     * 
     * @type {string}
     * @memberof CommunityModel
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommunityModel
     */
    members?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CommunityModel
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CommunityModel
     */
    executionDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CommunityModel
     */
    authorId?: string | null;
    /**
     * 
     * @type {UserModel}
     * @memberof CommunityModel
     */
    authorData?: UserModel | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommunityModel
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the CommunityModel interface.
 */
export function instanceOfCommunityModel(value: object): value is CommunityModel {
    return true;
}

export function CommunityModelFromJSON(json: any): CommunityModel {
    return CommunityModelFromJSONTyped(json, false);
}

export function CommunityModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityModel {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'members': json['members'] == null ? undefined : json['members'],
        'id': json['id'] == null ? undefined : json['id'],
        'executionDate': json['executionDate'] == null ? undefined : (new Date(json['executionDate'])),
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'authorData': json['authorData'] == null ? undefined : UserModelFromJSON(json['authorData']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CommunityModelToJSON(json: any): CommunityModel {
    return CommunityModelToJSONTyped(json, false);
}

export function CommunityModelToJSONTyped(value?: CommunityModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'members': value['members'],
        'id': value['id'],
        'executionDate': value['executionDate'] === null ? null : ((value['executionDate'] as any)?.toISOString()),
        'authorId': value['authorId'],
        'authorData': UserModelToJSON(value['authorData']),
        'tags': value['tags'],
    };
}

