/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';

/**
 * 
 * @export
 * @interface GroupModel
 */
export interface GroupModel {
    /**
     * 
     * @type {string}
     * @memberof GroupModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupModel
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupModel
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof GroupModel
     */
    executionDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GroupModel
     */
    authorId?: string | null;
    /**
     * 
     * @type {UserModel}
     * @memberof GroupModel
     */
    authorData?: UserModel | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupModel
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the GroupModel interface.
 */
export function instanceOfGroupModel(value: object): value is GroupModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupModelFromJSON(json: any): GroupModel {
    return GroupModelFromJSONTyped(json, false);
}

export function GroupModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'executionDate': json['executionDate'] == null ? undefined : (new Date(json['executionDate'])),
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'authorData': json['authorData'] == null ? undefined : UserModelFromJSON(json['authorData']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function GroupModelToJSON(json: any): GroupModel {
    return GroupModelToJSONTyped(json, false);
}

export function GroupModelToJSONTyped(value?: GroupModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'id': value['id'],
        'executionDate': value['executionDate'] == null ? value['executionDate'] : value['executionDate'].toISOString(),
        'authorId': value['authorId'],
        'authorData': UserModelToJSON(value['authorData']),
        'tags': value['tags'],
    };
}

