/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';

/**
 * 
 * @export
 * @interface LinkModel
 */
export interface LinkModel {
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    sourceType?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    sourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    targetType?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    targetId?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    metadata?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof LinkModel
     */
    executionDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof LinkModel
     */
    authorId?: string | null;
    /**
     * 
     * @type {UserModel}
     * @memberof LinkModel
     */
    authorData?: UserModel | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LinkModel
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the LinkModel interface.
 */
export function instanceOfLinkModel(value: object): value is LinkModel {
    return true;
}

export function LinkModelFromJSON(json: any): LinkModel {
    return LinkModelFromJSONTyped(json, false);
}

export function LinkModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkModel {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceType': json['sourceType'] == null ? undefined : json['sourceType'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'targetType': json['targetType'] == null ? undefined : json['targetType'],
        'targetId': json['targetId'] == null ? undefined : json['targetId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'id': json['id'] == null ? undefined : json['id'],
        'executionDate': json['executionDate'] == null ? undefined : (new Date(json['executionDate'])),
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'authorData': json['authorData'] == null ? undefined : UserModelFromJSON(json['authorData']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function LinkModelToJSON(json: any): LinkModel {
    return LinkModelToJSONTyped(json, false);
}

export function LinkModelToJSONTyped(value?: LinkModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceType': value['sourceType'],
        'sourceId': value['sourceId'],
        'targetType': value['targetType'],
        'targetId': value['targetId'],
        'metadata': value['metadata'],
        'id': value['id'],
        'executionDate': value['executionDate'] == null ? value['executionDate'] : value['executionDate'].toISOString(),
        'authorId': value['authorId'],
        'authorData': UserModelToJSON(value['authorData']),
        'tags': value['tags'],
    };
}

