/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface MessageHistoryModel
 */
export interface MessageHistoryModel {
    /**
     * 
     * @type {string}
     * @memberof MessageHistoryModel
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof MessageHistoryModel
     */
    previousContent: string;
    /**
     * 
     * @type {Date}
     * @memberof MessageHistoryModel
     */
    editedDate: Date;
    /**
     * 
     * @type {string}
     * @memberof MessageHistoryModel
     */
    id?: string;
}

export function instanceOfMessageHistoryModel(value: object): value is MessageHistoryModel {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('previousContent' in value) || value['previousContent'] === undefined) return false;
    if (!('editedDate' in value) || value['editedDate'] === undefined) return false;
    return true;
}

export function MessageHistoryModelFromJSON(json: any): MessageHistoryModel {
    return MessageHistoryModelFromJSONTyped(json, false);
}

export function MessageHistoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageHistoryModel {
    if (json == null) {
        return json;
    }
    return {

        'messageId': json['messageId'],
        'previousContent': json['previousContent'],
        'editedDate': (new Date(json['editedDate'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function MessageHistoryModelToJSON(json: any): MessageHistoryModel {
    return MessageHistoryModelToJSONTyped(json, false);
}

export function MessageHistoryModelToJSONTyped(value?: MessageHistoryModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'messageId': value['messageId'],
        'previousContent': value['previousContent'],
        'editedDate': value['editedDate'].toISOString(),
        'id': value['id'],
    };
}
