/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';

/**
 * 
 * @export
 * @interface PostModel
 */
export interface PostModel {
    /**
     * 
     * @type {string}
     * @memberof PostModel
     */
    to?: string;
    /**
     * 
     * @type {string}
     * @memberof PostModel
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof PostModel
     */
    seenDate?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PostModel
     */
    attachments: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof PostModel
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PostModel
     */
    executionDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PostModel
     */
    authorId?: string | null;
    /**
     * 
     * @type {UserModel}
     * @memberof PostModel
     */
    authorData?: UserModel | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PostModel
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the PostModel interface.
 */
export function instanceOfPostModel(value: object): value is PostModel {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('attachments' in value) || value['attachments'] === undefined) return false;
    return true;
}

export function PostModelFromJSON(json: any): PostModel {
    return PostModelFromJSONTyped(json, false);
}

export function PostModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostModel {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'message': json['message'],
        'seenDate': json['seenDate'] == null ? undefined : (new Date(json['seenDate'])),
        'attachments': json['attachments'] == null ? null : json['attachments'],
        'id': json['id'] == null ? undefined : json['id'],
        'executionDate': json['executionDate'] == null ? undefined : (new Date(json['executionDate'])),
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'authorData': json['authorData'] == null ? undefined : UserModelFromJSON(json['authorData']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function PostModelToJSON(json: any): PostModel {
    return PostModelToJSONTyped(json, false);
}

export function PostModelToJSONTyped(value?: PostModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'message': value['message'],
        'seenDate': value['seenDate'] == null ? value['seenDate'] : value['seenDate'].toISOString(),
        'attachments': value['attachments'],
        'id': value['id'],
        'executionDate': value['executionDate'] == null ? value['executionDate'] : value['executionDate'].toISOString(),
        'authorId': value['authorId'],
        'authorData': UserModelToJSON(value['authorData']),
        'tags': value['tags'],
    };
}

