/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionModelSelection
 */
export interface QuestionModelSelection {
}

/**
 * Check if a given object implements the QuestionModelSelection interface.
 */
export function instanceOfQuestionModelSelection(value: object): value is QuestionModelSelection {
    return true;
}

export function QuestionModelSelectionFromJSON(json: any): QuestionModelSelection {
    return QuestionModelSelectionFromJSONTyped(json, false);
}

export function QuestionModelSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionModelSelection {
    return json;
}

export function QuestionModelSelectionToJSON(json: any): QuestionModelSelection {
    return QuestionModelSelectionToJSONTyped(json, false);
}

export function QuestionModelSelectionToJSONTyped(value?: QuestionModelSelection | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

