// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Setia.Contexts.Base;

#nullable disable

namespace Base.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20240610155908_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("base")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Setia.Models.Base.AuditModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Audit", "base");
                });

            modelBuilder.Entity("Setia.Models.Base.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Notifications", "base");
                });

            modelBuilder.Entity("Setia.Models.Base.TagModel", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("ltree");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.HasKey("Tag");

                    b.ToTable("Tags", "base");

                    b.HasData(
                        new
                        {
                            Tag = "Role.Admin",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(3409)
                        },
                        new
                        {
                            Tag = "Controller.CRUD1.Get",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4095)
                        },
                        new
                        {
                            Tag = "Controller.CRUD1.Add",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4138)
                        },
                        new
                        {
                            Tag = "Controller.CRUD1.Update",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4179)
                        },
                        new
                        {
                            Tag = "Controller.CRUD1.Delete",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4201)
                        },
                        new
                        {
                            Tag = "Controller.Auth.Login",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4320)
                        },
                        new
                        {
                            Tag = "Controller.Auth.Register",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4342)
                        },
                        new
                        {
                            Tag = "Controller.Auth.CheckUserRights",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(4394)
                        },
                        new
                        {
                            Tag = "Controller.Helper.Upload",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(5113)
                        },
                        new
                        {
                            Tag = "Controller.Helper.GetUserTags",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(5137)
                        },
                        new
                        {
                            Tag = "Controller.Helper.GetUserProfile",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(5159)
                        },
                        new
                        {
                            Tag = "Controller.Helper.GetPostsForUser",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(5209)
                        },
                        new
                        {
                            Tag = "Controller.Helper.UpdateCurentUserAvatar",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(5232)
                        });
                });

            modelBuilder.Entity("Setia.Models.Base.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Signiture")
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "base");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e1ebce8-ef2e-4902-9be9-85a88f1601b5"),
                            Email = "",
                            ExecutionDate = new DateTime(2024, 6, 10, 18, 59, 8, 731, DateTimeKind.Utc).AddTicks(2933),
                            Name = "Test Name",
                            Password = "FD5CB51BAFD60F6FDBEDDE6E62C473DA6F247DB271633E15919BAB78A02EE9EB",
                            Tags = new List<string> { "Dragos" },
                            Username = "testUser"
                        });
                });

            modelBuilder.Entity("Setia.Models.Base.NotificationModel", b =>
                {
                    b.HasOne("Setia.Models.Base.UserModel", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId");

                    b.Navigation("UserData");
                });
#pragma warning restore 612, 618
        }
    }
}
