// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(SetiaContext))]
    partial class SetiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorityCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Id_LastUpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_CreatedBy");

                    b.HasIndex("Id_LastUpdateBy");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Models.UserModel", b =>
                {
                    b.HasOne("WebAPI.Models.UserModel", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("Id_CreatedBy");

                    b.HasOne("WebAPI.Models.UserModel", "LastUpdateBy")
                        .WithMany()
                        .HasForeignKey("Id_LastUpdateBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdateBy");
                });
#pragma warning restore 612, 618
        }
    }
}
