// <auto-generated />
using System;
using System.Collections.Generic;
using Main.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Main.Data.Migrations.Base
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("base")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Main.Data.Models.AuditModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorDataId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDataId");

                    b.ToTable("Audit", "base");
                });

            modelBuilder.Entity("Main.Data.Models.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AuthorDataId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("ExtraMessages")
                        .HasColumnType("hstore");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ToUserDataId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDataId");

                    b.HasIndex("ToUserDataId");

                    b.ToTable("Notifications", "base");
                });

            modelBuilder.Entity("Main.Data.Models.SettingsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorDataId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDataId");

                    b.ToTable("Settings", "base");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "",
                            ExecutionDate = new DateTime(2024, 10, 16, 20, 12, 4, 242, DateTimeKind.Utc).AddTicks(4102),
                            Key = "Client Name",
                            Tags = new List<string>(),
                            Value = "DragosClient"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "",
                            ExecutionDate = new DateTime(2024, 10, 16, 20, 12, 4, 242, DateTimeKind.Utc).AddTicks(4146),
                            Key = "Client BE URL",
                            Tags = new List<string>(),
                            Value = "https://localhost:44381"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "",
                            ExecutionDate = new DateTime(2024, 10, 16, 20, 12, 4, 242, DateTimeKind.Utc).AddTicks(4185),
                            Key = "Client Environment",
                            Tags = new List<string>(),
                            Value = "Development"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "",
                            ExecutionDate = new DateTime(2024, 10, 16, 20, 12, 4, 242, DateTimeKind.Utc).AddTicks(4214),
                            Key = "Client Colors",
                            Tags = new List<string>(),
                            Value = "2f42a6,845dbb"
                        });
                });

            modelBuilder.Entity("Main.Data.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AuthorDataId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<Guid>>("Friends")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("Saves")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("Signiture")
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDataId");

                    b.ToTable("Users", "base");
                });

            modelBuilder.Entity("Main.Data.Models.AuditModel", b =>
                {
                    b.HasOne("Main.Data.Models.AuditModel", "AuthorData")
                        .WithMany()
                        .HasForeignKey("AuthorDataId");

                    b.Navigation("AuthorData");
                });

            modelBuilder.Entity("Main.Data.Models.NotificationModel", b =>
                {
                    b.HasOne("Main.Data.Models.AuditModel", "AuthorData")
                        .WithMany()
                        .HasForeignKey("AuthorDataId");

                    b.HasOne("Main.Data.Models.AuditModel", "ToUserData")
                        .WithMany()
                        .HasForeignKey("ToUserDataId");

                    b.Navigation("AuthorData");

                    b.Navigation("ToUserData");
                });

            modelBuilder.Entity("Main.Data.Models.SettingsModel", b =>
                {
                    b.HasOne("Main.Data.Models.AuditModel", "AuthorData")
                        .WithMany()
                        .HasForeignKey("AuthorDataId");

                    b.Navigation("AuthorData");
                });

            modelBuilder.Entity("Main.Data.Models.UserModel", b =>
                {
                    b.HasOne("Main.Data.Models.AuditModel", "AuthorData")
                        .WithMany()
                        .HasForeignKey("AuthorDataId");

                    b.Navigation("AuthorData");
                });
#pragma warning restore 612, 618
        }
    }
}
