/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/adm': RouteRecordInfo<'/adm', '/adm', Record<never, never>, Record<never, never>>,
    '/collection': RouteRecordInfo<'/collection', '/collection', Record<never, never>, Record<never, never>>,
    '/download': RouteRecordInfo<'/download', '/download', Record<never, never>, Record<never, never>>,
    '/messanger': RouteRecordInfo<'/messanger', '/messanger', Record<never, never>, Record<never, never>>,
    '/MySpace/': RouteRecordInfo<'/MySpace/', '/MySpace', Record<never, never>, Record<never, never>>,
    '/MySpace/Friends/': RouteRecordInfo<'/MySpace/Friends/', '/MySpace/Friends', Record<never, never>, Record<never, never>>,
    '/MySpace/Friends/[id]': RouteRecordInfo<'/MySpace/Friends/[id]', '/MySpace/Friends/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/news': RouteRecordInfo<'/news', '/news', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/[id]': RouteRecordInfo<'/profile/[id]', '/profile/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/servers/': RouteRecordInfo<'/servers/', '/servers', Record<never, never>, Record<never, never>>,
    '/servers/[id]': RouteRecordInfo<'/servers/[id]', '/servers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/privacy-policy': RouteRecordInfo<'/settings/privacy-policy', '/settings/privacy-policy', Record<never, never>, Record<never, never>>,
    '/settings/recovery': RouteRecordInfo<'/settings/recovery', '/settings/recovery', Record<never, never>, Record<never, never>>,
    '/settings/terms-of-service': RouteRecordInfo<'/settings/terms-of-service', '/settings/terms-of-service', Record<never, never>, Record<never, never>>,
    '/tier_list/': RouteRecordInfo<'/tier_list/', '/tier_list', Record<never, never>, Record<never, never>>,
    '/tier_list/[id]': RouteRecordInfo<'/tier_list/[id]', '/tier_list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/vote-creator': RouteRecordInfo<'/vote-creator', '/vote-creator', Record<never, never>, Record<never, never>>,
  }
}
