/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiChatHistoryOtherUserIdGetRequest {
    otherUserId: string;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     */
    async apiChatHistoryOtherUserIdGetRaw(requestParameters: ApiChatHistoryOtherUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['otherUserId'] == null) {
            throw new runtime.RequiredError(
                'otherUserId',
                'Required parameter "otherUserId" was null or undefined when calling apiChatHistoryOtherUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Chat/History/{otherUserId}`;
        urlPath = urlPath.replace(`{${"otherUserId"}}`, encodeURIComponent(String(requestParameters['otherUserId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiChatHistoryOtherUserIdGet(requestParameters: ApiChatHistoryOtherUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiChatHistoryOtherUserIdGetRaw(requestParameters, initOverrides);
    }

}
