/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommunityModel,
} from '../models/index';
import {
    CommunityModelFromJSON,
    CommunityModelToJSON,
} from '../models/index';

export interface ApiCommunityAddPostRequest {
    communityModel: Array<CommunityModel>;
}

export interface ApiCommunityDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiCommunityGetGetRequest {
    items?: Array<CommunityModel>;
    pageSize?: number;
    pageNumber?: number;
}

export interface ApiCommunityUpdatePutRequest {
    communityModel: Array<CommunityModel>;
}

/**
 * 
 */
export class CommunityApi extends runtime.BaseAPI {

    /**
     */
    async apiCommunityAddPostRaw(requestParameters: ApiCommunityAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommunityModel>>> {
        if (requestParameters['communityModel'] == null) {
            throw new runtime.RequiredError(
                'communityModel',
                'Required parameter "communityModel" was null or undefined when calling apiCommunityAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Community/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['communityModel']!.map(CommunityModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommunityModelFromJSON));
    }

    /**
     */
    async apiCommunityAddPost(requestParameters: ApiCommunityAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommunityModel>> {
        const response = await this.apiCommunityAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommunityDeleteDeleteRaw(requestParameters: ApiCommunityDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommunityModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiCommunityDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Community/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommunityModelFromJSON));
    }

    /**
     */
    async apiCommunityDeleteDelete(requestParameters: ApiCommunityDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommunityModel>> {
        const response = await this.apiCommunityDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommunityGetGetRaw(requestParameters: ApiCommunityGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommunityModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Community/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommunityModelFromJSON));
    }

    /**
     */
    async apiCommunityGetGet(requestParameters: ApiCommunityGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommunityModel>> {
        const response = await this.apiCommunityGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommunityUpdatePutRaw(requestParameters: ApiCommunityUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['communityModel'] == null) {
            throw new runtime.RequiredError(
                'communityModel',
                'Required parameter "communityModel" was null or undefined when calling apiCommunityUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Community/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['communityModel']!.map(CommunityModelToJSON),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiCommunityUpdatePut(requestParameters: ApiCommunityUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.apiCommunityUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
