/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiUsersGetGetPageSizeParameter,
  GroupModel,
} from '../models/index';
import {
    ApiUsersGetGetPageSizeParameterFromJSON,
    ApiUsersGetGetPageSizeParameterToJSON,
    GroupModelFromJSON,
    GroupModelToJSON,
} from '../models/index';

export interface ApiGroupsAddPostRequest {
    groupModel: Array<GroupModel>;
}

export interface ApiGroupsDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiGroupsGetGetRequest {
    items?: Array<GroupModel>;
    pageSize?: ApiUsersGetGetPageSizeParameter;
    pageNumber?: ApiUsersGetGetPageSizeParameter;
}

export interface ApiGroupsUpdatePutRequest {
    groupModel: Array<GroupModel>;
}

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI {

    /**
     */
    async apiGroupsAddPostRaw(requestParameters: ApiGroupsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupModel>>> {
        if (requestParameters['groupModel'] == null) {
            throw new runtime.RequiredError(
                'groupModel',
                'Required parameter "groupModel" was null or undefined when calling apiGroupsAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Groups/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['groupModel']!.map(GroupModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupModelFromJSON));
    }

    /**
     */
    async apiGroupsAddPost(requestParameters: ApiGroupsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupModel>> {
        const response = await this.apiGroupsAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiGroupsDeleteDeleteRaw(requestParameters: ApiGroupsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiGroupsDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Groups/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupModelFromJSON));
    }

    /**
     */
    async apiGroupsDeleteDelete(requestParameters: ApiGroupsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupModel>> {
        const response = await this.apiGroupsDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiGroupsGetGetRaw(requestParameters: ApiGroupsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Groups/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupModelFromJSON));
    }

    /**
     */
    async apiGroupsGetGet(requestParameters: ApiGroupsGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupModel>> {
        const response = await this.apiGroupsGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiGroupsUpdatePutRaw(requestParameters: ApiGroupsUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUsersGetGetPageSizeParameter>> {
        if (requestParameters['groupModel'] == null) {
            throw new runtime.RequiredError(
                'groupModel',
                'Required parameter "groupModel" was null or undefined when calling apiGroupsUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Groups/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['groupModel']!.map(GroupModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUsersGetGetPageSizeParameterFromJSON(jsonValue));
    }

    /**
     */
    async apiGroupsUpdatePut(requestParameters: ApiGroupsUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUsersGetGetPageSizeParameter> {
        const response = await this.apiGroupsUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
