/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiUsersGetGetPageSizeParameter,
  LinkModel,
} from '../models/index';
import {
    ApiUsersGetGetPageSizeParameterFromJSON,
    ApiUsersGetGetPageSizeParameterToJSON,
    LinkModelFromJSON,
    LinkModelToJSON,
} from '../models/index';

export interface ApiLinksAddPostRequest {
    linkModel: Array<LinkModel>;
}

export interface ApiLinksDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiLinksGetGetRequest {
    items?: Array<LinkModel>;
    pageSize?: ApiUsersGetGetPageSizeParameter;
    pageNumber?: ApiUsersGetGetPageSizeParameter;
}

export interface ApiLinksUpdatePutRequest {
    linkModel: Array<LinkModel>;
}

/**
 * 
 */
export class LinksApi extends runtime.BaseAPI {

    /**
     */
    async apiLinksAddPostRaw(requestParameters: ApiLinksAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LinkModel>>> {
        if (requestParameters['linkModel'] == null) {
            throw new runtime.RequiredError(
                'linkModel',
                'Required parameter "linkModel" was null or undefined when calling apiLinksAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Links/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['linkModel']!.map(LinkModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LinkModelFromJSON));
    }

    /**
     */
    async apiLinksAddPost(requestParameters: ApiLinksAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LinkModel>> {
        const response = await this.apiLinksAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLinksDeleteDeleteRaw(requestParameters: ApiLinksDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LinkModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiLinksDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Links/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LinkModelFromJSON));
    }

    /**
     */
    async apiLinksDeleteDelete(requestParameters: ApiLinksDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LinkModel>> {
        const response = await this.apiLinksDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLinksGetGetRaw(requestParameters: ApiLinksGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LinkModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Links/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LinkModelFromJSON));
    }

    /**
     */
    async apiLinksGetGet(requestParameters: ApiLinksGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LinkModel>> {
        const response = await this.apiLinksGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLinksUpdatePutRaw(requestParameters: ApiLinksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUsersGetGetPageSizeParameter>> {
        if (requestParameters['linkModel'] == null) {
            throw new runtime.RequiredError(
                'linkModel',
                'Required parameter "linkModel" was null or undefined when calling apiLinksUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Links/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['linkModel']!.map(LinkModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUsersGetGetPageSizeParameterFromJSON(jsonValue));
    }

    /**
     */
    async apiLinksUpdatePut(requestParameters: ApiLinksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUsersGetGetPageSizeParameter> {
        const response = await this.apiLinksUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
