/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiUsersGetGetPageSizeParameter,
  NotificationModel,
} from '../models/index';
import {
    ApiUsersGetGetPageSizeParameterFromJSON,
    ApiUsersGetGetPageSizeParameterToJSON,
    NotificationModelFromJSON,
    NotificationModelToJSON,
} from '../models/index';

export interface ApiNotificationsAddPostRequest {
    notificationModel: Array<NotificationModel>;
}

export interface ApiNotificationsDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiNotificationsGetGetRequest {
    items?: Array<NotificationModel>;
    pageSize?: ApiUsersGetGetPageSizeParameter;
    pageNumber?: ApiUsersGetGetPageSizeParameter;
}

export interface ApiNotificationsMarkAsReadPostRequest {
    id?: string;
}

export interface ApiNotificationsSendGetRequest {
    notificationModel: NotificationModel;
}

export interface ApiNotificationsUpdatePutRequest {
    notificationModel: Array<NotificationModel>;
}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     */
    async apiNotificationsAddPostRaw(requestParameters: ApiNotificationsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NotificationModel>>> {
        if (requestParameters['notificationModel'] == null) {
            throw new runtime.RequiredError(
                'notificationModel',
                'Required parameter "notificationModel" was null or undefined when calling apiNotificationsAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Notifications/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['notificationModel']!.map(NotificationModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationModelFromJSON));
    }

    /**
     */
    async apiNotificationsAddPost(requestParameters: ApiNotificationsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NotificationModel>> {
        const response = await this.apiNotificationsAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiNotificationsDeleteDeleteRaw(requestParameters: ApiNotificationsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NotificationModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiNotificationsDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Notifications/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationModelFromJSON));
    }

    /**
     */
    async apiNotificationsDeleteDelete(requestParameters: ApiNotificationsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NotificationModel>> {
        const response = await this.apiNotificationsDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiNotificationsGetGetRaw(requestParameters: ApiNotificationsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NotificationModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Notifications/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationModelFromJSON));
    }

    /**
     */
    async apiNotificationsGetGet(requestParameters: ApiNotificationsGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NotificationModel>> {
        const response = await this.apiNotificationsGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiNotificationsGetUnreadGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NotificationModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Notifications/GetUnread`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationModelFromJSON));
    }

    /**
     */
    async apiNotificationsGetUnreadGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NotificationModel>> {
        const response = await this.apiNotificationsGetUnreadGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiNotificationsMarkAsReadPostRaw(requestParameters: ApiNotificationsMarkAsReadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Notifications/MarkAsRead`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiNotificationsMarkAsReadPost(requestParameters: ApiNotificationsMarkAsReadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiNotificationsMarkAsReadPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiNotificationsSendGetRaw(requestParameters: ApiNotificationsSendGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['notificationModel'] == null) {
            throw new runtime.RequiredError(
                'notificationModel',
                'Required parameter "notificationModel" was null or undefined when calling apiNotificationsSendGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Notifications/Send`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationModelToJSON(requestParameters['notificationModel']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiNotificationsSendGet(requestParameters: ApiNotificationsSendGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiNotificationsSendGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiNotificationsUpdatePutRaw(requestParameters: ApiNotificationsUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUsersGetGetPageSizeParameter>> {
        if (requestParameters['notificationModel'] == null) {
            throw new runtime.RequiredError(
                'notificationModel',
                'Required parameter "notificationModel" was null or undefined when calling apiNotificationsUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Notifications/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['notificationModel']!.map(NotificationModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUsersGetGetPageSizeParameterFromJSON(jsonValue));
    }

    /**
     */
    async apiNotificationsUpdatePut(requestParameters: ApiNotificationsUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUsersGetGetPageSizeParameter> {
        const response = await this.apiNotificationsUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
