/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiUsersGetGetPageSizeParameter,
  ParameterModel,
} from '../models/index';
import {
    ApiUsersGetGetPageSizeParameterFromJSON,
    ApiUsersGetGetPageSizeParameterToJSON,
    ParameterModelFromJSON,
    ParameterModelToJSON,
} from '../models/index';

export interface ApiParametersAddPostRequest {
    parameterModel: Array<ParameterModel>;
}

export interface ApiParametersDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiParametersGetGetRequest {
    items?: Array<ParameterModel>;
    pageSize?: ApiUsersGetGetPageSizeParameter;
    pageNumber?: ApiUsersGetGetPageSizeParameter;
}

export interface ApiParametersUpdatePutRequest {
    parameterModel: Array<ParameterModel>;
}

/**
 * 
 */
export class ParametersApi extends runtime.BaseAPI {

    /**
     */
    async apiParametersAddPostRaw(requestParameters: ApiParametersAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ParameterModel>>> {
        if (requestParameters['parameterModel'] == null) {
            throw new runtime.RequiredError(
                'parameterModel',
                'Required parameter "parameterModel" was null or undefined when calling apiParametersAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Parameters/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['parameterModel']!.map(ParameterModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParameterModelFromJSON));
    }

    /**
     */
    async apiParametersAddPost(requestParameters: ApiParametersAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ParameterModel>> {
        const response = await this.apiParametersAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiParametersDeleteDeleteRaw(requestParameters: ApiParametersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ParameterModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiParametersDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Parameters/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParameterModelFromJSON));
    }

    /**
     */
    async apiParametersDeleteDelete(requestParameters: ApiParametersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ParameterModel>> {
        const response = await this.apiParametersDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiParametersGetGetRaw(requestParameters: ApiParametersGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ParameterModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Parameters/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParameterModelFromJSON));
    }

    /**
     */
    async apiParametersGetGet(requestParameters: ApiParametersGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ParameterModel>> {
        const response = await this.apiParametersGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiParametersUpdatePutRaw(requestParameters: ApiParametersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUsersGetGetPageSizeParameter>> {
        if (requestParameters['parameterModel'] == null) {
            throw new runtime.RequiredError(
                'parameterModel',
                'Required parameter "parameterModel" was null or undefined when calling apiParametersUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Parameters/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['parameterModel']!.map(ParameterModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUsersGetGetPageSizeParameterFromJSON(jsonValue));
    }

    /**
     */
    async apiParametersUpdatePut(requestParameters: ApiParametersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUsersGetGetPageSizeParameter> {
        const response = await this.apiParametersUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
