/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiUsersGetGetPageSizeParameter,
  PostModel,
} from '../models/index';
import {
    ApiUsersGetGetPageSizeParameterFromJSON,
    ApiUsersGetGetPageSizeParameterToJSON,
    PostModelFromJSON,
    PostModelToJSON,
} from '../models/index';

export interface ApiPostsAddPostRequest {
    postModel: Array<PostModel>;
}

export interface ApiPostsDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiPostsGetGetRequest {
    items?: Array<PostModel>;
    pageSize?: ApiUsersGetGetPageSizeParameter;
    pageNumber?: ApiUsersGetGetPageSizeParameter;
}

export interface ApiPostsUpdatePutRequest {
    postModel: Array<PostModel>;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     */
    async apiPostsAddPostRaw(requestParameters: ApiPostsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PostModel>>> {
        if (requestParameters['postModel'] == null) {
            throw new runtime.RequiredError(
                'postModel',
                'Required parameter "postModel" was null or undefined when calling apiPostsAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Posts/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['postModel']!.map(PostModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostModelFromJSON));
    }

    /**
     */
    async apiPostsAddPost(requestParameters: ApiPostsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PostModel>> {
        const response = await this.apiPostsAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsDeleteDeleteRaw(requestParameters: ApiPostsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PostModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiPostsDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Posts/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostModelFromJSON));
    }

    /**
     */
    async apiPostsDeleteDelete(requestParameters: ApiPostsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PostModel>> {
        const response = await this.apiPostsDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsGetGetRaw(requestParameters: ApiPostsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PostModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Posts/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostModelFromJSON));
    }

    /**
     */
    async apiPostsGetGet(requestParameters: ApiPostsGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PostModel>> {
        const response = await this.apiPostsGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsUpdatePutRaw(requestParameters: ApiPostsUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUsersGetGetPageSizeParameter>> {
        if (requestParameters['postModel'] == null) {
            throw new runtime.RequiredError(
                'postModel',
                'Required parameter "postModel" was null or undefined when calling apiPostsUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Posts/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['postModel']!.map(PostModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUsersGetGetPageSizeParameterFromJSON(jsonValue));
    }

    /**
     */
    async apiPostsUpdatePut(requestParameters: ApiPostsUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUsersGetGetPageSizeParameter> {
        const response = await this.apiPostsUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
