/* tslint:disable */
/* eslint-disable */
/**
 * Main | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QuestionModel,
} from '../models/index';
import {
    QuestionModelFromJSON,
    QuestionModelToJSON,
} from '../models/index';

export interface ApiQuestionAnswersAddPostRequest {
    questionModel: Array<QuestionModel>;
}

export interface ApiQuestionAnswersDeleteDeleteRequest {
    requestBody: Array<string>;
}

export interface ApiQuestionAnswersGetGetRequest {
    items?: Array<QuestionModel>;
    pageSize?: number;
    pageNumber?: number;
}

export interface ApiQuestionAnswersUpdatePutRequest {
    questionModel: Array<QuestionModel>;
}

/**
 * 
 */
export class QuestionAnswersApi extends runtime.BaseAPI {

    /**
     */
    async apiQuestionAnswersAddPostRaw(requestParameters: ApiQuestionAnswersAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QuestionModel>>> {
        if (requestParameters['questionModel'] == null) {
            throw new runtime.RequiredError(
                'questionModel',
                'Required parameter "questionModel" was null or undefined when calling apiQuestionAnswersAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/QuestionAnswers/Add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['questionModel']!.map(QuestionModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionModelFromJSON));
    }

    /**
     */
    async apiQuestionAnswersAddPost(requestParameters: ApiQuestionAnswersAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuestionModel>> {
        const response = await this.apiQuestionAnswersAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiQuestionAnswersDeleteDeleteRaw(requestParameters: ApiQuestionAnswersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QuestionModel>>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling apiQuestionAnswersDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/QuestionAnswers/Delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionModelFromJSON));
    }

    /**
     */
    async apiQuestionAnswersDeleteDelete(requestParameters: ApiQuestionAnswersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuestionModel>> {
        const response = await this.apiQuestionAnswersDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiQuestionAnswersGetGetRaw(requestParameters: ApiQuestionAnswersGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QuestionModel>>> {
        const queryParameters: any = {};

        if (requestParameters['items'] != null) {
            queryParameters['Items'] = requestParameters['items'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/QuestionAnswers/Get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionModelFromJSON));
    }

    /**
     */
    async apiQuestionAnswersGetGet(requestParameters: ApiQuestionAnswersGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuestionModel>> {
        const response = await this.apiQuestionAnswersGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiQuestionAnswersUpdatePutRaw(requestParameters: ApiQuestionAnswersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['questionModel'] == null) {
            throw new runtime.RequiredError(
                'questionModel',
                'Required parameter "questionModel" was null or undefined when calling apiQuestionAnswersUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/QuestionAnswers/Update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['questionModel']!.map(QuestionModelToJSON),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiQuestionAnswersUpdatePut(requestParameters: ApiQuestionAnswersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.apiQuestionAnswersUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
