/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CRUDT: typeof import('./src/components/CRUDT.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginComponent: typeof import('./src/components/auth/LoginComponent.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordRecoveryComponent: typeof import('./src/components/auth/recovery/PasswordRecoveryComponent.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RegisterComponent: typeof import('./src/components/auth/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
    TriStateCheckbox: typeof import('primevue/tristatecheckbox')['default']
    UsernameRecoveryComponent: typeof import('./src/components/auth/recovery/UsernameRecoveryComponent.vue')['default']
  }
}
