/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    CareerView: typeof import('./src/views/CareerView.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CRUDT: typeof import('./src/components/CRUDT.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeshertRegion: typeof import('./src/components/regions/DeshertRegion.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DownloadView: typeof import('./src/views/DownloadView.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginComponent: typeof import('./src/components/authentication/LoginComponent.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewsView: typeof import('./src/views/NewsView.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    PageNotFound: typeof import('./src/views/PageNotFound.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    PasswordRecoveryComponent: typeof import('./src/components/recovery/PasswordRecoveryComponent.vue')['default']
    PiratesRegion: typeof import('./src/components/regions/PiratesRegion.vue')['default']
    PlayersLeaderboard: typeof import('./src/components/PlayersLeaderboard.vue')['default']
    RecoveryView: typeof import('./src/views/RecoveryView.vue')['default']
    RegisterComponent: typeof import('./src/components/authentication/RegisterComponent.vue')['default']
    RegisterView: typeof import('./src/views/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    StoryChapter: typeof import('./src/components/StoryChapter.vue')['default']
    SumeruRegion: typeof import('./src/components/regions/SumeruRegion.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
    TriStateCheckbox: typeof import('primevue/tristatecheckbox')['default']
    UniverseView: typeof import('./src/views/UniverseView.vue')['default']
    UsernameRecoveryComponent: typeof import('./src/components/recovery/UsernameRecoveryComponent.vue')['default']
    VikingsRegion: typeof import('./src/components/regions/VikingsRegion.vue')['default']
    WorldMap: typeof import('./src/components/regions/WorldMap.vue')['default']
  }
}
