/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/adm': RouteRecordInfo<'/adm', '/adm', Record<never, never>, Record<never, never>>,
    '/career': RouteRecordInfo<'/career', '/career', Record<never, never>, Record<never, never>>,
    '/download': RouteRecordInfo<'/download', '/download', Record<never, never>, Record<never, never>>,
    '/news': RouteRecordInfo<'/news', '/news', Record<never, never>, Record<never, never>>,
    '/privacy-policy': RouteRecordInfo<'/privacy-policy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/quizz-creator': RouteRecordInfo<'/quizz-creator', '/quizz-creator', Record<never, never>, Record<never, never>>,
    '/recovery': RouteRecordInfo<'/recovery', '/recovery', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/terms-of-service': RouteRecordInfo<'/terms-of-service', '/terms-of-service', Record<never, never>, Record<never, never>>,
  }
}
