name: Deploy DEV

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

################################################################################
      - name: Setup Frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build Frontend
        run: |
          cd FE
          ls
          npm ci
          npm run build
################################################################################
      - name: Setup Backend
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Backend
        run: |
          cd BE/Main
          ls
          dotnet restore

          dotnet user-secrets set "DBConnectionStrings" "${{ secrets.DB_CONNECTION_STRING }}"
          dotnet user-secrets set "DBTech" "PgSQL"
          dotnet user-secrets set "CryptKey" "uwXk6g6Kxr166TGji80ICeI0udlzm7hT"
          dotnet user-secrets set "Origin" "http://localhost:3000"
          dotnet user-secrets set "Server" "https://localhost:44381"
          
          dotnet build -c Release
          dotnet publish -c Release -o ../WebApp
################################################################################
      - name: Copy Frontend to Backend
        run: |
          cp -R FE/dist/* BE/WebApp/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iis-deploy-${{ vars.NAME }}
          path: BE/WebApp/**
          if-no-files-found: error
          retention-days: 1
