# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Restore NPM
      run: |
        cd UI
        npm install
      
    - name: Restore .NET
      run: dotnet restore
      
    - name: Build .NET
      run: dotnet build --no-restore

    - name: Build NPM
      run: npm run build
      
    - name: Test .NET
      run: dotnet test --no-build --verbosity normal
